### ISSUE TITLE
NLTK:  resource stopwords not found

### ISSUE THREAD

**Issue by joereynolds** [hotshot07/whatsapp_analyser#2]
When trying to analyse my `chat.txt` file, it fails on nltk unable to find `stopwords`

```
: python3 main.py android ../chat.txt 
Processing data ...
Creating word cloud ...
Traceback (most recent call last):
  File "/home/joe/code/envvv/whatsapp/lib/python3.6/site-packages/nltk/corpus/util.py", line 83, in __load
    root = nltk.data.find("{}/{}".format(self.subdir, zip_name))
  File "/home/joe/code/envvv/whatsapp/lib/python3.6/site-packages/nltk/data.py", line 585, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/joe/nltk_data'
    - '/home/joe/code/envvv/whatsapp/nltk_data'
    - '/home/joe/code/envvv/whatsapp/share/nltk_data'
    - '/home/joe/code/envvv/whatsapp/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 59, in <module>
    make_wordcloud(1)
  File "/home/joe/code/envvv/whatsapp/app/whatsapp_analyser/wc.py", line 35, in make_wordcloud
    all_stopwords = list(stopwords.words('english'))
  File "/home/joe/code/envvv/whatsapp/lib/python3.6/site-packages/nltk/corpus/util.py", line 120, in __getattr__
    self.__load()
  File "/home/joe/code/envvv/whatsapp/lib/python3.6/site-packages/nltk/corpus/util.py", line 85, in __load
    raise e
  File "/home/joe/code/envvv/whatsapp/lib/python3.6/site-packages/nltk/corpus/util.py", line 80, in __load
    root = nltk.data.find("{}/{}".format(self.subdir, self.__name))
  File "/home/joe/code/envvv/whatsapp/lib/python3.6/site-packages/nltk/data.py", line 585, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/joe/nltk_data'
    - '/home/joe/code/envvv/whatsapp/nltk_data'
    - '/home/joe/code/envvv/whatsapp/share/nltk_data'
    - '/home/joe/code/envvv/whatsapp/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

```

**Comment by joereynolds** [comment]
Just as a note, I fixed this manually with

```
python3 -m nltk.downloader stopwords
```

I think this should be added as a step in the README or somehow do it for the user automatically

**Comment by hotshot07** [comment]
Oh that's great thank you I'll add that to the readme, I was about to make a list just based on the English stopwords so users don't have to download it manually, but if this works I'll just update the readme as of now.

**Comment by alexcroox** [comment]
I don't think the stop words downloaded are used? I think it just uses the "hinglish" file.

https://github.com/hotshot07/whatsapp_analyser/blob/master/wc.py#L36-L40

**Comment by joereynolds** [comment]
The line above that uses the stopwords corpus 

```
    all_stopwords = list(stopwords.words('english'))
```

**Comment by alexcroox** [comment]
yes but it's overwritten by `all_stopwords = hindi_stoplist + custom_list`

**Comment by hotshot07** [comment]
I just updated the code so that it doesn't use the nltk.stopwords . Shouldn't be an issue now.
